version: '3'
services:
  app:
    image: node:16
    command: bash -c "npm start"
    restart: unless-stopped
    volumes:
    - '.:/usr/src/app'
    working_dir: /usr/src/app
    ports:
      - '4000:4000'
    links:
      - mongo
  mongo:
    restart: unless-stopped
    image: mongo
    ports:
      - '27017:27017'
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network